"""1st

Revision ID: 53999fcb42b4
Revises: 6b8f79174f6c
Create Date: 2026-01-28 14:47:53.740421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53999fcb42b4'
down_revision: Union[str, Sequence[str], None] = '6b8f79174f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('proposition_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'proposition_id')
    # ### end Alembic commands ###
